//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddRate_CatAddRate
    {
        public int Id { get; set; }
        public int AddRateId { get; set; }
        public int CategoryAddId { get; set; }
        public Nullable<int> CategoryAddRateId { get; set; }
        public double Price { get; set; }
        public int DiscountId { get; set; }
        public Nullable<int> TypeDiscountId { get; set; }
    
        public virtual AddRate AddRate { get; set; }
        public virtual CategoryAddRate CategoryAddRate { get; set; }
        public virtual TypeDiscount TypeDiscount { get; set; }
    }
}
