//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.FormCheck = new HashSet<FormCheck>();
        }
    
        public int Id { get; set; }
        public int CatCompId { get; set; }
        public Nullable<int> CategoryComputerId { get; set; }
        public System.DateTime DateTimeBegin { get; set; }
        public System.DateTime DateTimeEnd { get; set; }
        public int UsersId { get; set; }
        public bool IsBusy { get; set; }
    
        public virtual CategoryComputer CategoryComputer { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormCheck> FormCheck { get; set; }
    }
}
