//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormCheck
    {
        public int Id { get; set; }
        public System.DateTime DateRate { get; set; }
        public int RateId { get; set; }
        public int PayId { get; set; }
        public Nullable<int> TypaPayId { get; set; }
        public int CatCompId { get; set; }
        public Nullable<int> CategoryComputerId { get; set; }
        public int AddRateId { get; set; }
        public int ClientId { get; set; }
        public Nullable<int> UsersID { get; set; }
        public int BookingId { get; set; }
        public bool isEarly { get; set; }
        public string Description { get; set; }
    
        public virtual AddRate AddRate { get; set; }
        public virtual Booking Booking { get; set; }
        public virtual CategoryComputer CategoryComputer { get; set; }
        public virtual Rate Rate { get; set; }
        public virtual TypePay TypePay { get; set; }
        public virtual Users Users { get; set; }
    }
}
