//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameComputer
    {
        public int Id { get; set; }
        public int ComputerId { get; set; }
        public int GameId { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual Game Game { get; set; }
    }
}
